export const countries = [
  { "code": "AF", "label": "Afghanistan", "phone": "93", "currency": "AFN" },
  { "code": "AL", "label": "Albania", "phone": "355", "currency": "ALL" },
  { "code": "DZ", "label": "Algeria", "phone": "213", "currency": "DZD" },
  { "code": "AD", "label": "Andorra", "phone": "376", "currency": "EUR" },
  { "code": "AO", "label": "Angola", "phone": "244", "currency": "AOA" },
  { "code": "AG", "label": "Antigua and Barbuda", "phone": "1-268", "currency": "XCD" },
  { "code": "AR", "label": "Argentina", "phone": "54", "currency": "ARS" },
  { "code": "AM", "label": "Armenia", "phone": "374", "currency": "AMD" },
  { "code": "AU", "label": "Australia", "phone": "61", "currency": "AUD" },
  { "code": "AT", "label": "Austria", "phone": "43", "currency": "EUR" },
  { "code": "AZ", "label": "Azerbaijan", "phone": "994", "currency": "AZN" },
  { "code": "BS", "label": "Bahamas", "phone": "1-242", "currency": "BSD" },
  { "code": "BH", "label": "Bahrain", "phone": "973", "currency": "BHD" },
  { "code": "BD", "label": "Bangladesh", "phone": "880", "currency": "BDT" },
  { "code": "BB", "label": "Barbados", "phone": "1-246", "currency": "BBD" },
  { "code": "BY", "label": "Belarus", "phone": "375", "currency": "BYN" },
  { "code": "BE", "label": "Belgium", "phone": "32", "currency": "EUR" },
  { "code": "BZ", "label": "Belize", "phone": "501", "currency": "BZD" },
  { "code": "BJ", "label": "Benin", "phone": "229", "currency": "XOF" },
  { "code": "BT", "label": "Bhutan", "phone": "975", "currency": "BTN" },
  { "code": "BO", "label": "Bolivia", "phone": "591", "currency": "BOB" },
  { "code": "BA", "label": "Bosnia and Herzegovina", "phone": "387", "currency": "BAM" },
  { "code": "BW", "label": "Botswana", "phone": "267", "currency": "BWP" },
  { "code": "BR", "label": "Brazil", "phone": "55", "currency": "BRL" },
  { "code": "BN", "label": "Brunei Darussalam", "phone": "673", "currency": "BND" },
  { "code": "BG", "label": "Bulgaria", "phone": "359", "currency": "BGN" },
  { "code": "BF", "label": "Burkina Faso", "phone": "226", "currency": "XOF" },
  { "code": "BI", "label": "Burundi", "phone": "257", "currency": "BIF" },
  { "code": "CV", "label": "Cabo Verde", "phone": "238", "currency": "CVE" },
  { "code": "KH", "label": "Cambodia", "phone": "855", "currency": "KHR" },
  { "code": "CM", "label": "Cameroon", "phone": "237", "currency": "XAF" },
  { "code": "CA", "label": "Canada", "phone": "1", "currency": "CAD" },
  { "code": "CF", "label": "Central African Republic", "phone": "236", "currency": "XAF" },
  { "code": "TD", "label": "Chad", "phone": "235", "currency": "XAF" },
  { "code": "CL", "label": "Chile", "phone": "56", "currency": "CLP" },
  { "code": "CN", "label": "China", "phone": "86", "currency": "CNY" },
  { "code": "CO", "label": "Colombia", "phone": "57", "currency": "COP" },
  { "code": "KM", "label": "Comoros", "phone": "269", "currency": "KMF" },
  { "code": "CD", "label": "Congo, Democratic Republic of the", "phone": "243", "currency": "CDF" },
  { "code": "CG", "label": "Congo, Republic of the", "phone": "242", "currency": "XAF" },
  { "code": "CR", "label": "Costa Rica", "phone": "506", "currency": "CRC" },
  { "code": "CI", "label": "Côte d'Ivoire", "phone": "225", "currency": "XOF" },
  { "code": "HR", "label": "Croatia", "phone": "385", "currency": "EUR" },
  { "code": "CU", "label": "Cuba", "phone": "53", "currency": "CUP" },
  { "code": "CY", "label": "Cyprus", "phone": "357", "currency": "EUR" },
  { "code": "CZ", "label": "Czechia", "phone": "420", "currency": "CZK" },
  { "code": "DK", "label": "Denmark", "phone": "45", "currency": "DKK" },
  { "code": "DJ", "label": "Djibouti", "phone": "253", "currency": "DJF" },
  { "code": "DM", "label": "Dominica", "phone": "1-767", "currency": "XCD" },
  { "code": "DO", "label": "Dominican Republic", "phone": "1-809", "currency": "DOP" },
  { "code": "EC", "label": "Ecuador", "phone": "593", "currency": "USD" },
  { "code": "EG", "label": "Egypt", "phone": "20", "currency": "EGP" },
  { "code": "SV", "label": "El Salvador", "phone": "503", "currency": "USD" },
  { "code": "GQ", "label": "Equatorial Guinea", "phone": "240", "currency": "XAF" },
  { "code": "ER", "label": "Eritrea", "phone": "291", "currency": "ERN" },
  { "code": "EE", "label": "Estonia", "phone": "372", "currency": "EUR" },
  { "code": "SZ", "label": "Eswatini", "phone": "268", "currency": "SZL" },
  { "code": "ET", "label": "Ethiopia", "phone": "251", "currency": "ETB" },
  { "code": "FJ", "label": "Fiji", "phone": "679", "currency": "FJD" },
  { "code": "FI", "label": "Finland", "phone": "358", "currency": "EUR" },
  { "code": "FR", "label": "France", "phone": "33", "currency": "EUR" },
  { "code": "GA", "label": "Gabon", "phone": "241", "currency": "XAF" },
  { "code": "GM", "label": "Gambia", "phone": "220", "currency": "GMD" },
  { "code": "GE", "label": "Georgia", "phone": "995", "currency": "GEL" },
  { "code": "DE", "label": "Germany", "phone": "49", "currency": "EUR" },
  { "code": "GH", "label": "Ghana", "phone": "233", "currency": "GHS" },
  { "code": "GR", "label": "Greece", "phone": "30", "currency": "EUR" },
  { "code": "GD", "label": "Grenada", "phone": "1-473", "currency": "XCD" },
  { "code": "GT", "label": "Guatemala", "phone": "502", "currency": "GTQ" },
  { "code": "GN", "label": "Guinea", "phone": "224", "currency": "GNF" },
  { "code": "GW", "label": "Guinea-Bissau", "phone": "245", "currency": "XOF" },
  { "code": "GY", "label": "Guyana", "phone": "592", "currency": "GYD" },
  { "code": "HT", "label": "Haiti", "phone": "509", "currency": "HTG" },
  { "code": "HN", "label": "Honduras", "phone": "504", "currency": "HNL" },
  { "code": "HU", "label": "Hungary", "phone": "36", "currency": "HUF" },
  { "code": "IS", "label": "Iceland", "phone": "354", "currency": "ISK" },
  { "code": "IN", "label": "India", "phone": "91", "currency": "INR" },
  { "code": "ID", "label": "Indonesia", "phone": "62", "currency": "IDR" },
  { "code": "IR", "label": "Iran, Islamic Republic of", "phone": "98", "currency": "IRR" },
  { "code": "IQ", "label": "Iraq", "phone": "964", "currency": "IQD" },
  { "code": "IE", "label": "Ireland", "phone": "353", "currency": "EUR" },
  { "code": "IL", "label": "Israel", "phone": "972", "currency": "ILS" },
  { "code": "IT", "label": "Italy", "phone": "39", "currency": "EUR" },
  { "code": "JM", "label": "Jamaica", "phone": "1-876", "currency": "JMD" },
  { "code": "JP", "label": "Japan", "phone": "81", "currency": "JPY" },
  { "code": "JO", "label": "Jordan", "phone": "962", "currency": "JOD" },
  { "code": "KZ", "label": "Kazakhstan", "phone": "7", "currency": "KZT" },
  { "code": "KE", "label": "Kenya", "phone": "254", "currency": "KES" },
  { "code": "KI", "label": "Kiribati", "phone": "686", "currency": "AUD" },
  { "code": "KP", "label": "Korea, Democratic People's Republic of", "phone": "850", "currency": "KPW" },
  { "code": "KR", "label": "Korea, Republic of", "phone": "82", "currency": "KRW" },
  { "code": "KW", "label": "Kuwait", "phone": "965", "currency": "KWD" },
  { "code": "KG", "label": "Kyrgyzstan", "phone": "996", "currency": "KGS" },
  { "code": "LA", "label": "Lao People's Democratic Republic", "phone": "856", "currency": "LAK" },
  { "code": "LV", "label": "Latvia", "phone": "371", "currency": "EUR" },
  { "code": "LB", "label": "Lebanon", "phone": "961", "currency": "LBP" },
  { "code": "LS", "label": "Lesotho", "phone": "266", "currency": "LSL" },
  { "code": "LR", "label": "Liberia", "phone": "231", "currency": "LRD" },
  { "code": "LY", "label": "Libya", "phone": "218", "currency": "LYD" },
  { "code": "LI", "label": "Liechtenstein", "phone": "423", "currency": "CHF" },
  { "code": "LT", "label": "Lithuania", "phone": "370", "currency": "EUR" },
  { "code": "LU", "label": "Luxembourg", "phone": "352", "currency": "EUR" },
  { "code": "MG", "label": "Madagascar", "phone": "261", "currency": "MGA" },
  { "code": "MW", "label": "Malawi", "phone": "265", "currency": "MWK" },
  { "code": "MY", "label": "Malaysia", "phone": "60", "currency": "MYR" },
  { "code": "MV", "label": "Maldives", "phone": "960", "currency": "MVR" },
  { "code": "ML", "label": "Mali", "phone": "223", "currency": "XOF" },
  { "code": "MT", "label": "Malta", "phone": "356", "currency": "EUR" },
  { "code": "MH", "label": "Marshall Islands", "phone": "692", "currency": "USD" },
  { "code": "MR", "label": "Mauritania", "phone": "222", "currency": "MRU" },
  { "code": "MU", "label": "Mauritius", "phone": "230", "currency": "MUR" },
  { "code": "MX", "label": "Mexico", "phone": "52", "currency": "MXN" },
  { "code": "FM", "label": "Micronesia, Federated States of", "phone": "691", "currency": "USD" },
  { "code": "MD", "label": "Moldova, Republic of", "phone": "373", "currency": "MDL" },
  { "code": "MC", "label": "Monaco", "phone": "377", "currency": "EUR" },
  { "code": "MN", "label": "Mongolia", "phone": "976", "currency": "MNT" },
  { "code": "ME", "label": "Montenegro", "phone": "382", "currency": "EUR" },
  { "code": "MA", "label": "Morocco", "phone": "212", "currency": "MAD" },
  { "code": "MZ", "label": "Mozambique", "phone": "258", "currency": "MZN" },
  { "code": "MM", "label": "Myanmar", "phone": "95", "currency": "MMK" },
  { "code": "NA", "label": "Namibia", "phone": "264", "currency": "NAD" },
  { "code": "NR", "label": "Nauru", "phone": "674", "currency": "AUD" },
  { "code": "NP", "label": "Nepal", "phone": "977", "currency": "NPR" },
  { "code": "NL", "label": "Netherlands", "phone": "31", "currency": "EUR" },
  { "code": "NZ", "label": "New Zealand", "phone": "64", "currency": "NZD" },
  { "code": "NI", "label": "Nicaragua", "phone": "505", "currency": "NIO" },
  { "code": "NE", "label": "Niger", "phone": "227", "currency": "XOF" },
  { "code": "NG", "label": "Nigeria", "phone": "234", "currency": "NGN" },
  { "code": "MK", "label": "North Macedonia", "phone": "389", "currency": "MKD" },
  { "code": "NO", "label": "Norway", "phone": "47", "currency": "NOK" },
  { "code": "OM", "label": "Oman", "phone": "968", "currency": "OMR" },
  { "code": "PK", "label": "Pakistan", "phone": "92", "currency": "PKR" },
  { "code": "PW", "label": "Palau", "phone": "680", "currency": "USD" },
  { "code": "PA", "label": "Panama", "phone": "507", "currency": "PAB" },
  { "code": "PG", "label": "Papua New Guinea", "phone": "675", "currency": "PGK" },
  { "code": "PY", "label": "Paraguay", "phone": "595", "currency": "PYG" },
  { "code": "PE", "label": "Peru", "phone": "51", "currency": "PEN" },
  { "code": "PH", "label": "Philippines", "phone": "63", "currency": "PHP" },
  { "code": "PL", "label": "Poland", "phone": "48", "currency": "PLN" },
  { "code": "PT", "label": "Portugal", "phone": "351", "currency": "EUR" },
  { "code": "QA", "label": "Qatar", "phone": "974", "currency": "QAR" },
  { "code": "RO", "label": "Romania", "phone": "40", "currency": "RON" },
  { "code": "RU", "label": "Russian Federation", "phone": "7", "currency": "RUB" },
  { "code": "RW", "label": "Rwanda", "phone": "250", "currency": "RWF" },
  { "code": "KN", "label": "Saint Kitts and Nevis", "phone": "1-869", "currency": "XCD" },
  { "code": "LC", "label": "Saint Lucia", "phone": "1-758", "currency": "XCD" },
  { "code": "VC", "label": "Saint Vincent and the Grenadines", "phone": "1-784", "currency": "XCD" },
  { "code": "WS", "label": "Samoa", "phone": "685", "currency": "WST" },
  { "code": "SM", "label": "San Marino", "phone": "378", "currency": "EUR" },
  { "code": "ST", "label": "Sao Tome and Principe", "phone": "239", "currency": "STN" },
  { "code": "SA", "label": "Saudi Arabia", "phone": "966", "currency": "SAR" },
  { "code": "SN", "label": "Senegal", "phone": "221", "currency": "XOF" },
  { "code": "RS", "label": "Serbia", "phone": "381", "currency": "RSD" },
  { "code": "SC", "label": "Seychelles", "phone": "248", "currency": "SCR" },
  { "code": "SL", "label": "Sierra Leone", "phone": "232", "currency": "SLL" },
  { "code": "SG", "label": "Singapore", "phone": "65", "currency": "SGD" },
  { "code": "SK", "label": "Slovakia", "phone": "421", "currency": "EUR" },
  { "code": "SI", "label": "Slovenia", "phone": "386", "currency": "EUR" },
  { "code": "SB", "label": "Solomon Islands", "phone": "677", "currency": "SBD" },
  { "code": "SO", "label": "Somalia", "phone": "252", "currency": "SOS" },
  { "code": "ZA", "label": "South Africa", "phone": "27", "currency": "ZAR" },
  { "code": "SS", "label": "South Sudan", "phone": "211", "currency": "SSP" },
  { "code": "ES", "label": "Spain", "phone": "34", "currency": "EUR" },
  { "code": "LK", "label": "Sri Lanka", "phone": "94", "currency": "LKR" },
  { "code": "SD", "label": "Sudan", "phone": "249", "currency": "SDG" },
  { "code": "SR", "label": "Suriname", "phone": "597", "currency": "SRD" },
  { "code": "SE", "label": "Sweden", "phone": "46", "currency": "SEK" },
  { "code": "CH", "label": "Switzerland", "phone": "41", "currency": "CHF" },
  { "code": "SY", "label": "Syrian Arab Republic", "phone": "963", "currency": "SYP" },
  { "code": "TW", "label": "Taiwan, Province of China", "phone": "886", "currency": "TWD" },
  { "code": "TJ", "label": "Tajikistan", "phone": "992", "currency": "TJS" },
  { "code": "TZ", "label": "Tanzania, United Republic of", "phone": "255", "currency": "TZS" },
  { "code": "TH", "label": "Thailand", "phone": "66", "currency": "THB" },
  { "code": "TL", "label": "Timor-Leste", "phone": "670", "currency": "USD" },
  { "code": "TG", "label": "Togo", "phone": "228", "currency": "XOF" },
  { "code": "TO", "label": "Tonga", "phone": "676", "currency": "TOP" },
  { "code": "TT", "label": "Trinidad and Tobago", "phone": "1-868", "currency": "TTD" },
  { "code": "TN", "label": "Tunisia", "phone": "216", "currency": "TND" },
  { "code": "TR", "label": "Turkey", "phone": "90", "currency": "TRY" },
  { "code": "TM", "label": "Turkmenistan", "phone": "993", "currency": "TMT" },
  { "code": "TV", "label": "Tuvalu", "phone": "688", "currency": "AUD" },
  { "code": "UG", "label": "Uganda", "phone": "256", "currency": "UGX" },
  { "code": "UA", "label": "Ukraine", "phone": "380", "currency": "UAH" },
  { "code": "AE", "label": "United Arab Emirates", "phone": "971", "currency": "AED" },
  { "code": "GB", "label": "United Kingdom", "phone": "44", "currency": "GBP" },
  { "code": "US", "label": "United States", "phone": "1", "currency": "USD" },
  { "code": "UY", "label": "Uruguay", "phone": "598", "currency": "UYU" },
  { "code": "UZ", "label": "Uzbekistan", "phone": "998", "currency": "UZS" },
  { "code": "VU", "label": "Vanuatu", "phone": "678", "currency": "VUV" },
  { "code": "VE", "label": "Venezuela, Bolivarian Republic of", "phone": "58", "currency": "VES" },
  { "code": "VN", "label": "Viet Nam", "phone": "84", "currency": "VND" },
  { "code": "YE", "label": "Yemen", "phone": "967", "currency": "YER" },
  { "code": "ZM", "label": "Zambia", "phone": "260", "currency": "ZMW" },
  { "code": "ZW", "label": "Zimbabwe", "phone": "263", "currency": "ZWL" }
];